### PR TITLE
Add various Artisan snippets

### PR DESCRIPTION
**Pull request by jeanpierreb**

### CODE REVIEW

**Comment by patricksamson** [comment]
Thanks! Looks good, but I would change a few things : 
- `tabTriggers` should be prefixed with `Console::` and match the function name. EG : `Console::ask`
- I think there a few functions missing, see [here](http://laravel.com/api/5.1/Illuminate/Console/Command.html) (`warn()`, `comment()`, `table()`, ...)

**Comment by jeanpierreb** [comment]
My pleasure, Lykegenes. The `Console::` prefix definitely makes sense although I think it might not be as intuitive to a newbie and it's debatable weather that's actually easier to type. I tend to think of snippets more like tab completion but I'll update this to fit your convention.

**Comment by jeanpierreb** [comment]
How is it now?

**Comment by patricksamson** [comment]
Perfect, thank you! I made a huge cleanup in the last few days, I still have a few things to touch up before I publish the new version. I will also add a cheatsheet in the Readme for a quick reference.

If you're looking for autocompletion, the best package I've found is [CodeComplice](https://github.com/spectacles/CodeComplice), which is a fork of [SublimeCodeIntel](https://github.com/SublimeCodeIntel/SublimeCodeIntel).

I created this package as a shortcut to Laravel's (incomplete and inconsistent) documentation. I know what is possible to be done, but I can never remember the function names, their syntax or their parameters!

**Pull request merged**
